global:
  smtp_smarthost: "mailhog:1025"
  smtp_from: "alertmanager@weather-pipeline.local"
  smtp_require_tls: false

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  receiver: "email-mailhog"
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: "email-mailhog"
      matchers:
        - severity="critical"
      group_wait: 10s
      repeat_interval: 1h
    - receiver: "email-mailhog"
      matchers:
        - severity="warning"
      group_wait: 1m
      repeat_interval: 4h

receivers:
  - name: "email-mailhog"
    email_configs:
      - to: "admin@weather-pipeline.local"
        send_resolved: true
        html: '{{ template "email.html" . }}'
        headers:
          Subject: '{{ template "email.subject" . }}'
