networks:
  pipeline-network:
    driver: bridge

services:
  dlt-runner:
    build:
      context: ../..
      dockerfile: ingestion/Dockerfile
    image: weather-pipeline-dlt:1.0.0
    profiles:
      - build-only

  dbt-runner:
    build:
      context: ../..
      dockerfile: transformations/Dockerfile
    image: weather-pipeline-dbt:1.0.0
    profiles:
      - build-only

  soda-runner:
    build:
      context: ../..
      dockerfile: data_quality/Dockerfile
    image: weather-pipeline-soda:1.0.0
    profiles:
      - build-only

