name: weather_pipeline
version: "1.0.0"

profile: weather_pipeline

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

vars:
  dbt_utils_dispatch_list: [dbt_utils]
  s3_bucket: "{{ env_var('MINIO_BUCKET_NAME', 'data-lake') }}"
  s3_raw_prefix: "raw/openweather/data"

models:
  weather_pipeline:
    staging:
      +materialized: table
      +database: pg
      +schema: staging
    staging_quarantine:
      +materialized: table
      +database: pg
      +schema: staging_quarantine
    core:
      +materialized: table
      +database: pg
      +schema: core
    marts:
      +materialized: table
      +database: pg
      +schema: mart
    analytic:
      +materialized: table
      +database: pg
      +schema: analytic
  elementary:
    +schema: elementary

on-run-end:
  - "{{ dbt_utils.log_info('Pipeline run completed') }}"
