apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-pipeline-team
    receivers:
      - uid: email-pipeline
        type: email
        settings:
          addresses: "admin@weather-pipeline.local"
          singleEmail: true
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: email-pipeline-team
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: email-pipeline-team
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h
        continue: false
      - receiver: email-pipeline-team
        matchers:
          - severity = warning
        group_wait: 1m
        group_interval: 5m
        repeat_interval: 4h
        continue: false
